// Synthetic sample transcripts covering realistic consulting/engineering
// scenarios, used to seed the library so the app is demoable end to end
// without real Synchrone recordings.

export const SAMPLE_TRANSCRIPTS = [
  {
    file_name: "2026-03-04_checkout-latency-bugfix.mp3",
    full_text: `Alright, let's go through the checkout latency incident from last week. We started seeing P95 response times on the checkout endpoint climb from around two hundred milliseconds to almost four seconds during peak traffic. The first thing we did was pull the distributed traces, and it was pretty clear the time was being spent in the payment service, not in the frontend or the gateway. When we looked closer at the payment service code, we found it was doing an N plus one query pattern against the orders table. For every line item in a cart, it was issuing a separate database round trip to fetch the associated discount rules instead of batching that into a single query. Under low traffic this was invisible because the loop only ran a handful of times, but once a client started running a flash sale with carts averaging twenty two items, that single request was firing over twenty sequential queries against a connection pool that was already under pressure. We fixed it by rewriting the discount lookup to use a single batched query with an IN clause, and we added a covering index on the discount rules table keyed on product ID and region. After deploying the fix, P95 dropped back under two hundred fifty milliseconds even during a synthetic load test at three times normal peak volume. We also added an alert on per request query count for the payment service so if this pattern regresses again, we catch it in staging instead of in production during a client's flash sale. One follow up item is to audit the other services for the same N plus one anti pattern, since this codebase has a few places where the same junior engineer wrote similar loops. We should probably add a lint rule or a code review checklist item specifically calling this out. Client was happy once we showed them the before and after latency graphs, and we used this as a talking point for the broader performance audit we pitched them for next quarter.`,
  },
  {
    file_name: "2026-04-11_client-escalation-data-migration.mp3",
    full_text: `This call is about the escalation we got from the client's VP of operations regarding the customer data migration project. The core issue is that the migration from their legacy on premise CRM to the new cloud platform was supposed to finish by the end of March, and we're now three weeks past that date with about eighty five percent of records migrated. The VP escalated because their sales team can't get a unified view of customer history, and it's affecting their quarterly renewal conversations. Digging into why we're behind, the main blocker turned out to be data quality in the legacy system. There are roughly forty thousand customer records with malformed phone numbers, duplicate entries under slightly different spellings of company names, and orphaned contact records pointing to accounts that no longer exist. Our original migration script assumed clean foreign key relationships, and it started failing silently on about twelve percent of records, which we didn't catch until QA flagged the discrepancy in record counts. What we did to de escalate: first, we gave the VP a transparent accounting of exactly which record categories were affected and why, rather than a vague apology, which really helped rebuild trust. Second, we built a deduplication and validation pass that runs before the migration step, using fuzzy matching on company name and normalized phone number format. Third, we proposed a phased cutover where the ninety two percent of clean records migrate immediately, and the remaining problem records get a dedicated two week remediation sprint with a client side data steward reviewing edge cases with us daily. The client agreed to that phased plan, and it actually became a case study we can reference internally about handling data quality surprises in legacy migrations. Key lesson for future migration scoping: always run a data profiling pass against the legacy source during discovery, before committing to a fixed migration date, because assuming clean data is the single biggest risk in this kind of engagement.`,
  },
  {
    file_name: "2026-05-19_architecture-monolith-to-microservices.mp3",
    full_text: `Today's session is about the architecture decision for splitting the client's monolith ahead of their Black Friday traffic spike. Their current application is a single Rails monolith handling catalog, cart, checkout, inventory, and recommendations all in one deployable unit, and last year during Black Friday they had two full outages because a memory leak in the recommendations module took down the entire app, including checkout, which obviously was the worst possible failure mode. The team proposed a full microservices rewrite, but given we only have four months before this year's Black Friday, we pushed back on that as too risky. Instead we recommended a strangler fig approach: extract just the two highest risk modules, recommendations and inventory, into separate services, and leave catalog, cart, and checkout in the monolith for now since those have been stable. Recommendations gets extracted first because it's the thing that caused last year's outage, and it's a read heavy, stateless workload that's a natural fit for horizontal scaling behind its own load balancer. We're deploying it as a separate service with its own database replica, so a crash or slowdown there can no longer take down checkout. Inventory gets extracted second because it has the most write contention during flash sales, and we're introducing an event queue between checkout and inventory so stock decrements happen asynchronously instead of blocking the checkout request path. We also insisted on a circuit breaker pattern at the API gateway so if either extracted service becomes slow or unavailable, the monolith degrades gracefully, for example showing cached recommendations instead of failing the whole page. We ran a load test simulating three times last year's peak traffic with the recommendations service artificially killed mid test, and checkout stayed fully operational, which was the actual success criterion the client cared about, not architectural purity. The remaining monolith split can happen after Black Friday once we're not under a hard deadline.`,
  },
  {
    file_name: "2026-06-02_onboarding-vpn-access-questions.mp3",
    full_text: `This is a quick recording to capture the recurring onboarding question we keep getting from new engineers joining the client's team, so we stop answering it ad hoc in Slack every single week. The question is almost always some version of, why can't I access the staging database or the internal admin tools even though my VPN shows connected. The root cause is that the client uses a split tunnel VPN configuration, where only traffic to specific internal CIDR ranges gets routed through the VPN, and everything else, including DNS for some internal hostnames, goes over the regular internet connection. New hires typically get VPN connectivity approved on their first day, but the separate ticket for DNS resolver configuration and the internal certificate authority root cert installation is a manual step that IT only processes once a day, usually the following morning. So there's this predictable gap where someone is connected to the VPN, can ping internal IP addresses directly, but can't resolve internal hostnames or hit anything over HTTPS because their machine doesn't trust the internal certificate authority yet. We've now written this up as a standing onboarding checklist item: day one, request VPN and DNS resolver and CA cert all in the same ticket instead of as separate follow up requests, since bundling them means IT processes all three in one batch instead of three separate queues. We also added a five minute troubleshooting script that new hires can run themselves, which checks VPN status, DNS resolution for three known internal hostnames, and whether the CA cert is present in the system trust store, and tells them in plain language which of the three is missing. Since we started handing out this checklist and script two months ago, the average time from first day to fully working internal access dropped from about a day and a half to under three hours, and we stopped getting the same question repeated in the client's engineering Slack channel every week.`,
  },
  {
    file_name: "2026-07-08_third-party-api-schema-drift.mp3",
    full_text: `Let's walk through the data pipeline failure from two weeks ago that paged the on call engineer at two in the morning. The nightly ETL job that pulls order data from the client's third party logistics provider started failing every run, and the error was a generic deserialization exception that didn't immediately point at the cause. After some digging we found the logistics provider had silently changed their API response schema, renaming a field from shipment status to fulfillment status, and changing the enum values from upper case strings like SHIPPED to lower case ones like shipped, without any version bump or changelog notice, and without notifying any of their integration partners. Our pipeline's deserialization layer was using strict schema validation with no tolerance for unknown or renamed fields, which is generally good practice for catching real data problems, but in this case it meant the entire nightly batch failed instead of just the specific records affected by the field rename, so we lost visibility into which orders had actually shipped for almost eighteen hours. Short term fix was straightforward: update the schema mapping to accept both the old and new field names and both casing conventions for the enum, and ship that as a hotfix within a few hours of diagnosis. The more important structural fix was changing our ingestion pattern for all third party API integrations, not just this one, to decouple raw ingestion from schema validation. Now we land the raw JSON payload in a staging table completely unvalidated, and run schema validation and transformation as a separate downstream step. That way, if a provider changes their schema again, we still capture the raw data and can backfill after publishing a fix, instead of silently dropping data during the outage window. We also asked the client to push their logistics provider to commit to a versioned API with deprecation notices, which they're negotiating into the contract renewal. This incident is now the reference example we use with clients when we recommend the raw landing zone pattern for any external API dependency.`,
  },
];
